### PR TITLE
added lfs True to maven.yml

### PR DESCRIPTION
**Pull request by ajohnsson95**
Added lfs true for large files to be properly checked out

### CODE REVIEW

**Review by Charlottehenriksson — DISMISSED** [review]
Looks to be adding lfs correctly, nice!

**Review by kappsegla — CHANGES_REQUESTED** [review]
Shouldn't this update be in the release.yml file? maven.yml is for CI and doesn't build the docker images.

**Review by alexander-tf2fan — DISMISSED** [review]
Looks fine to me.  Assures that rows 15-28 happens, no matter what.

**Review by kappsegla — APPROVED** [review]

**Review by Tlereng — APPROVED** [review]
Code looks nice and tidy, very good

**Comment by Demppas** [comment]
I trust Martin

**Pull request merged**
