### PR TITLE
 Automatic release build

### PR DESCRIPTION
**Pull request by Philippevial**
Used following resources to resolve the issue #21

https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

### CODE REVIEW

**Comment by LordRekishi** [comment]
The problem with Qodana might be that you need to merge the latest main branch into your branch. It includes some fixes to remove printStack and such that Qodana is complaining about.

**Comment by Philippevial** [comment]
> The problem with Qodana might be that you need to merge the latest main branch into your branch. It includes some fixes to remove printStack and such that Qodana is complaining about.

Thanks, I did what you suggested and it worked like a charm!

**Review by ErikssonF — APPROVED** [review]
I created a new repository for testing this pull request and after pulling the latest version through the terminal in intelliJ it created a new image in Docker. Looks like everything is working as expected!

**Review by Yuriks1 — APPROVED** [review]
Looks good to me, well done!

**Pull request merged**
