### PR TITLE
Create maven.yml

### LINKED ISSUE #2: Github actions
Configure automatic build and running of tests when doing pull requests against main branch.

### PR DESCRIPTION
**Pull request by HelenaHalldinITHS**
This commit will fix #2

### CODE REVIEW

**Comment by DarkendHall** [comment]
We need to rerun the checks. Which I think only @kappsegla can do.

It seems to have failed because there was no pom.xml file to find at that time, this was added in #6.

**Comment by LordRekishi** [comment]
Is it possible to update your local branch and make a new commit with the pom.xml?

**Comment by DarkendHall** [comment]
I now realize that it wont matter if we rerun the checks, because there still wont be a pom.xml in this branch.

**Comment by kappsegla** [comment]
> 

I have triggered a rerun

**Comment by kappsegla** [comment]
The build fails with error message:

No file in /home/runner/work/storm/storm matched to [**/pom.xml], make sure you have checked out the target repository

**Review by DarkendHall — COMMENTED** [review]
Code looks good.

Not sure if merging "main" into "Issue2" is a good practice though.

**Comment by kappsegla** [comment]
> Code looks good.
> 
> Not sure if merging "main" into "Issue2" is a good practice though.

There are two ways of updating our feature branch from main. Merge or rebase.
https://timwise.co.uk/2019/10/14/merge-vs-rebase/

**Comment by HelenaHalldinITHS** [comment]
How else whould I keep my branch issue2 up to date otherwise? :)

**Comment by DarkendHall** [comment]
I thought it was best to use rebase, but it seems both are fine.

**Review by DarkendHall — APPROVED** [review]
Nice work :)

**Comment by kappsegla** [comment]
Rebase is good. So the alternative here would be to run:
git fetch
git rebase origin/master
git push --force-with-lease

Since we are changing the commits and redoing them we would need to use force push to update the commits on the remote.
This problem will hopefully not happen too often for us in the project. Was a problem now with the first commit before being a maven project.

**Review by ChristianLofqvist — APPROVED** [review]
Looks good, great job

**Pull request merged**
