### PR TITLE
Parse HTTP Request Headers

### LINKED ISSUE #11: Parsing HTTP request headers
When communicating with a web server it's common to use HTTP as protocol. A request header consists of multiple lines of text and ends with an empty line. We need to have some functionality that can convert this header information into a more friendly format. From a string or a list of strings to some sort of Header object that can be queried for information.
The first line has request type followed by the file and folder we are looking for and ends with the version of the HTTP protocol.
The following lines consists of a key, value pair separated with

Ex:
GET /home.html HTTP/1.1
Host: developer.mozilla.org
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Connection: keep-alive

https://developer.mozilla.org/en-US/docs/Glossary/Request_header

### PR DESCRIPTION
**Pull request by Vimbayinashe**
Resolves #11

### CODE REVIEW

**Comment by HelenaHalldinITHS** [comment]
Looks good at a first glance! I will deep dive in the issue and go through the list Martin sent and get back with a review(hopefully this afternoon).

**Comment by Vimbayinashe** [comment]
> Looks good at a first glance! I will deep dive in the issue and go through the list Martin sent and get back with a review(hopefully this afternoon).

Thank-you! :slightly_smiling_face:

**Comment by ToniKaru** [comment]
Looks really clean and concise so far! I too will look a bit more and get back to you later today. 
I will also leave the pull request up since I see at least one more person wants to do a code review.

**Comment by Vimbayinashe** [comment]
> Looks really clean and concise so far! I too will look a bit more and get back to you later today. I will also leave the pull request up since I see at least one more person wants to do a code review.

Thanks Toni!

**Comment by LordRekishi** [comment]
@Vimbayinashe 

The "Host:" section of the request headers. Is that supposed to point at the domain name of our website? Or to the webhotell of our website? Or how come we point to "developer.mozilla.org"?

**Comment by LordRekishi** [comment]
@Vimbayinashe 

According to the documentation here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept 
The last part of the following request header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8" should be "*/*;q=0.8" rather then "/;q=0.8". Or have you found this not to make any difference?

**Comment by Vimbayinashe** [comment]
> @Vimbayinashe
> 
> The "Host:" section of the request headers. Is that supposed to point at the domain name of our website? Or to the webhotell of our website? Or how come we point to "developer.mozilla.org"?

As far as I understand the server receives the request headers from the client and we are parsing them to extract the request line(first line) and then any key-value pairs after that.

I have merely used the example of request headers that was in the original issue description for testing purposes. It should be compatible but I can change it.

**Comment by LordRekishi** [comment]
@kappsegla 

Martin, is this something we need to consider? Do we need the application/xhtml+xml part of the Accept header? Is this for our pom.xml file to be recognized? 

Found this quote at: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

> **text/html**
> All HTML content should be served with this type. Alternative MIME types for XHTML (like application/xhtml+xml) are mostly useless nowadays.
> 
> Note: Use application/xml or application/xhtml+xml if you want XML's strict parsing rules, <![CDATA[…]]> sections, or elements that aren't from HTML/SVG/MathML namespaces.

**Comment by LordRekishi** [comment]
> > @Vimbayinashe
> > The "Host:" section of the request headers. Is that supposed to point at the domain name of our website? Or to the webhotell of our website? Or how come we point to "developer.mozilla.org"?
> 
> As far as I understand the server receives the request headers from the client and we are parsing them to extract the request line(first line) and then any key-value pairs after that.
> 
> I have merely used the example of request headers that was in the original issue description for testing purposes. It should be compatible but I can change it.

That's fine! I just want to understand fully what each of the headers are supposed to do and if we should make it more specific for our server or not at this point. What do you say @kappsegla ?

**Comment by Vimbayinashe** [comment]
> @kappsegla
> 
> Martin, is this something we need to consider? Do we need the application/xhtml+xml part of the Accept header? Is this for our pom.xml file to be recognized?
> 
> Found this quote at: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
> 
> > **text/html**
> > All HTML content should be served with this type. Alternative MIME types for XHTML (like application/xhtml+xml) are mostly useless nowadays.
> > Note: Use application/xml or application/xhtml+xml if you want XML's strict parsing rules,  sections, or elements that aren't from HTML/SVG/MathML namespaces.

_"The Accept request-header field can be used to specify certain media types which are acceptable for the response. Accept headers can be used to indicate that the request is specifically limited to a small set of desired types, as in the case of a request for an in-line image._  
Source: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1"

**Comment by Vimbayinashe** [comment]
> > > @Vimbayinashe
> > > The "Host:" section of the request headers. Is that supposed to point at the domain name of our website? Or to the webhotell of our website? Or how come we point to "developer.mozilla.org"?
> > 
> > 
> > As far as I understand the server receives the request headers from the client and we are parsing them to extract the request line(first line) and then any key-value pairs after that.
> > I have merely used the example of request headers that was in the original issue description for testing purposes. It should be compatible but I can change it.
> 
> That's fine! I just want to understand fully what each of the headers are supposed to do and if we should make it more specific for our server or not at this point. What do you say @kappsegla ?

This is an older version of w3.org's HTTP/1.1 Protocol but I still found it helpful: https://www.w3.org/Protocols/rfc2616/rfc2616.html
I found this to be an easier read: https://code.tutsplus.com/tutorials/http-headers-for-dummies--net-8039
Finally, a list of all possible headers: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
I hope this helps! 😄

**Comment by HelenaHalldinITHS** [comment]
A good soultion to the problem Vimbay!
A few things:
- There are no test for when the string is unvalid (row 14 in HttpParser is never reached)
- Mabey the method getRequestHeaders is a bit large, I thing some parts could be extracted to its own methods. (So it is easier to read and maintain)
- SonarLint recomends that you add a privet constructor to hide the implicit public one. I think its a good idea.

**Review by HelenaHalldinITHS — COMMENTED** [review]
A good soultion to the problem Vimbay!
A few things:

- There are no test for when the string is unvalid (row 14 in HttpParser is never reached)
- Mabey the method getRequestHeaders is a bit large, I thing some parts could be extracted to its own methods. (So it is easier to read and maintain)
- SonarLint recomends that you add a privet constructor to hide the implicit public one. I think its a good idea.

**Comment by ToniKaru** [comment]
I agree with all of Helena's suggestions. The only other thing I might add is:
- maybe change is the magic number '3' in validRequest() to a constant, like "PROPERTY_COUNT" or something. It is pretty readable anyway though.

**Comment by HelenaHalldinITHS** [comment]
> I agree with all of Helena's suggestions. The only other thing I might add is:
> 
> * maybe change is the magic number '3' in validRequest() to a constant, like "PROPERTY_COUNT" or something. It is pretty readable anyway though.

Good idea Toni!

**Comment by ToniKaru** [comment]
Note: I corrected the assignee to Vimbay and me as a reviewer.
(I used the Intellij interface earlier to assign myself as a code reviewer. I realized just now that it did not work as desired.)

**Comment by LordRekishi** [comment]
> A good soultion to the problem Vimbay! A few things:
> 
> * There are no test for when the string is unvalid (row 14 in HttpParser is never reached)
> * Mabey the method getRequestHeaders is a bit large, I thing some parts could be extracted to its own methods. (So it is easier to read and maintain)
> * SonarLint recomends that you add a privet constructor to hide the implicit public one. I think its a good idea.

We could extract the Map creation and stream to its own method perhaps?

**Comment by kappsegla** [comment]
> 

There are a lot of header names available and programmers can also create there own names with a value so a parser method like this shouldn't really care about what the keys are named. Just parse them as long as they are valid with a key name a separator in the form of : and then a value. If we want to handle different requests headers in special ways it's a problem for code further downstream in our server. There we can write special code that checks if a header exists and what value it has.

**Comment by LordRekishi** [comment]
If Qodana still doesn't work, maybe you haven't merged in the new version of the main branch? I think it got updated just a few minutes ago.

**Comment by LordRekishi** [comment]
> > 
> 
> There are a lot of header names available and programmers can also create there own names with a value so a parser method like this shouldn't really care about what the keys are named. Just parse them as long as they are valid with a key name a separator in the form of : and then a value. If we want to handle different requests headers in special ways it's a problem for code further downstream in our server. There we can write special code that checks if a header exists and what value it has.

Thanks! Of course Vimbay's tests are just that, tests. So I guess I shouldn't worry too much about what they include now.

**Comment by Vimbayinashe** [comment]
> If Qodana still doesn't work, maybe you haven't merged in the new version of the main branch? I think it got updated just a few minutes ago.

Thank-you; I was very worried 😅

**Comment by LordRekishi** [comment]
2 suspicious problems were detected during Sanity Check. Probably there are some troubles with corresponding inspections. 

```
File            Inspection                                         Severity Count problems
HttpParser.java Java annotator                                     Critical 2    
```

Grouping problems by severity: High: 3
```
Name                                               Severity Count problems
Call to 'printStackTrace()'                        High     3   
```

Didn't someone fix the printStackTrace() and use the logger instead?
Not sure what this about Jana annotator is?

**Review by ToniKaru — APPROVED** [review]
All comments I gave are already taken care of.  Quick turn around, nice!

**Comment by LordRekishi** [comment]
> All comments I gave are already taken care of. Quick turn around, nice!

Vimbay is on the ball! :D

**Comment by LordRekishi** [comment]
> 2 suspicious problems were detected during Sanity Check. Probably there are some troubles with corresponding inspections.
> 
> ```
> File            Inspection                                         Severity Count problems
> HttpParser.java Java annotator                                     Critical 2    
> ```
> 
> Grouping problems by severity: High: 3
> 
> ```
> Name                                               Severity Count problems
> Call to 'printStackTrace()'                        High     3   
> ```
> 
> Didn't someone fix the printStackTrace() and use the logger instead? Not sure what this about Jana annotator is?

Issue #40 should solve this problem. Asked them for a status update.

**Review by LordRekishi — APPROVED** [review]
Looks great! Good work @Vimbayinashe

**Pull request merged**
