### PR TITLE
Change the setter methods to void type

### PR DESCRIPTION
**Pull request by Kouroshkt**
I changed the Setter's methods to void type in Configuration.java.

### CODE REVIEW

**Review by Mattan41 — COMMENTED** [review]
Could you explain to me why the change of design pattern?

**Comment by Kouroshkt** [comment]
They had return value and Setter methods have no return they make an opration.

**Review by Mattan41 — APPROVED** [review]
void version is best practice for Setters.

**Review by yrlacornelia — APPROVED** [review]
looks better to me, good job!

**Pull request merged**
